### ISSUE TITLE
how to make particle already emitted  not follow emit transform?

### ISSUE THREAD

**Issue by wanwanyahoo** [mob-sakai/ParticleEffectForUGUI#47] opened 2019-04-28 09:36 UTC
how to make particle already emitted  not follow emit transform?
I try simulation space to world but is wont't work after add ui particle script

**Comment by mob-sakai** [comment] 2019-04-29 04:06
Hi @DiegoGal
Thank you for reporting. :)

I would like to know more information on this issue.
Can you submit a small reproducible project for this issue?

**Comment by mob-sakai** [comment] 2019-04-29 04:07
Hi @wanwanyahoo
Thank you for reporting. :)

I would like to know more information on this issue.
Can you submit a small reproducible project for this issue?

**Comment by ALPSquid** [comment] 2019-05-01 08:18
Hi @mob-sakai 
I've identified the same issue with world space particles and it's very simple to reproduce. The issue being that already emitted particles don't stay in their world position when the particle system transform is moved.

**Steps**
1. Create a normal particle system (no UI Particle component) and set the simulation space to world.
2. Move the particle system transform. 
	- Notice how already emitted particles stay in the current position regardless of where the transform is moved. This is the expected behaviour.
3. Add a UI Particle component.
4. Move the particle system transform.
	- Notice how already emitted particles move relative to where the transform is moved. This is not the expected behaviour.
	
Commit 68da045 broke this behaviour as removing the added positioning code (Ln 305 - 325) makes world space particles behave as expected.

**Comment by mob-sakai** [comment] 2019-05-01 11:30
Please tell me more informations.
* Unity version
* ParticleEffectForUGUI version
* Platforms (Editor[Windows/Mac]/Standalone[Windows/Mac]/iOS/Android)
* etc...

**Comment by mob-sakai** [comment] 2019-05-01 11:31
@wanwanyahoo 
Thanks.
Please tell me more informations about this issue.
* Unity version
* ParticleEffectForUGUI version
* Platforms (Editor[Windows/Mac]/Standalone[Windows/Mac]/iOS/Android)
* etc...

**Comment by mob-sakai** [comment] 2019-05-01 11:32
@ALPSquid @wanwanyahoo 
Thanks.
Please tell me more informations about this issue.
* Unity version
* ParticleEffectForUGUI version
* Platforms (Editor[Windows/Mac]/Standalone[Windows/Mac]/iOS/Android)
* etc...

**Comment by wanwanyahoo** [comment] 2019-05-01 11:53
Thank you for reply so quickly.

Unity version:2018.3.13
particleeffectforugui version: 2.2.0
platform:windows 10 unity editor



发自我的 iPhone

**Comment by ALPSquid** [comment] 2019-05-01 13:10
Unity version: 2018.3.8f1
ParticleEffectForUGUI version: 2.2.1
Platform: Editor - Windows 10

**Comment by mob-sakai** [comment] 2019-05-02 02:01
Unity version: 2018.3.10f1
ParticleEffectForUGUI version: 2.2.1
Platform: Editor - Mac

Hmm...
In my environment, it seems to work well.
![May-02-2019 10-47-13](https://user-images.githubusercontent.com/12690315/57053397-b2c49f00-6cc8-11e9-9432-cdcb1e7bc607.gif)

[test.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3136506/test.unitypackage.zip)

Can you submit a small reproducible project for this issue?

**Comment by mob-sakai** [comment] 2019-05-02 02:03
Unity version: 2018.3.10f1
ParticleEffectForUGUI version: 2.2.1
Platform: Editor - Mac

Hmm...
In my environment, it seems to work well.
![May-02-2019 10-47-13](https://user-images.githubusercontent.com/12690315/57053397-b2c49f00-6cc8-11e9-9432-cdcb1e7bc607.gif)

![image](https://user-images.githubusercontent.com/12690315/57053567-d6d4b000-6cc9-11e9-8b3a-0ba6f1c21987.png)

[test.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3136506/test.unitypackage.zip)

@wanwanyahoo  @ALPSquid 
Can you submit a small reproducible project for this issue?

**Comment by mob-sakai** [comment] 2019-05-02 04:24
Oh, this issue is reproduced in my environment when scaling mode is set to `Local`.

**Comment by wanwanyahoo** [comment] 2019-05-02 07:22
simulation mode need set to world

发自我的 iPhone

**Comment by mob-sakai** [comment] 2019-05-07 12:04
@wanwanyahoo @ALPSquid 
What's RenderMode do you use?
* Screen Space - Overlay
* Screen Space - Camera
* World Space - Camera

**Comment by ALPSquid** [comment] 2019-05-07 12:42
@mob-sakai I'm using Screen Space - Camera

**Comment by wanwanyahoo** [comment] 2019-05-07 13:58
screen space-camera

发自我的 iPhone

**Comment by mob-sakai** [comment] 2019-05-07 15:03
I have a good news!
I found a more accurate calculation model and it will solve this issue!

**Before**
![May-07-2019 23-59-50](https://user-images.githubusercontent.com/12690315/57310164-4b717980-7124-11e9-8721-335fe74ceaa6.gif)


**After**
![May-07-2019 23-54-12](https://user-images.githubusercontent.com/12690315/57310168-4dd3d380-7124-11e9-9d0a-a90e078e483a.gif)

**Comment by mob-sakai** [comment] 2019-05-07 15:11
@wanwanyahoo @ALPSquid 
Import this package and test it.
If there is no problem, it will be released as v2.3.0. :)
[v2.3.0-pre.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3153284/v2.3.0-pre.unitypackage.zip)

**Comment by wanwanyahoo** [comment] 2019-05-08 01:49
Thank you very much.I will give feedbacks after testing.

发自我的 iPhone

**Comment by ALPSquid** [comment] 2019-05-08 08:32
> @wanwanyahoo @ALPSquid
> Import this package and test it.
> If there is no problem, it will be released as v2.3.0. :)
> [v2.3.0-pre.unitypackage.zip](https://github.com/mob-sakai/ParticleEffectForUGUI/files/3153284/v2.3.0-pre.unitypackage.zip)

@mob-sakai
That seems to be working great, cheers!

**Closed** 2019-05-08 14:34 UTC
Labels: question
