### ISSUE TITLE
Particle Sub Emitter not showing when start game, only show when deactive and active again.

### ISSUE THREAD

**Issue by nntgam** [mob-sakai/ParticleEffectForUGUI#148] opened 2021-02-16 10:39 UTC
**Describe the bug**
Particle Sub Emitter not showing when the game start, only show when deactive and active again.

**To Reproduce**
1. Put the prefab particle on canvas
2. Play the game
3. The sub emitter not show
4. Deactive and Active again
5. the sub emitter will show

**Package**
https://drive.google.com/file/d/1Q8FPP_A7BoEwhdeLKyLix3axSdVpZ-Le/view

**Environment (please complete the following information):**
 - Version 3.3.0
 - Platform: Editor
 - Unity version: 2019.2.21f1
 - Build options: mono

**Comment by mob-sakai** [comment] 2021-02-17 10:18
The issue is reproduced on my environment.

**Comment by topher-mcbearslayer** [comment] 2021-02-17 22:01
This issue was driving me crazy, thought I was doing something wrong:
https://github.com/mob-sakai/ParticleEffectForUGUI/issues/127

Same issue here.

**Comment by nntgam** [comment] 2021-02-18 02:06
I see your ticket @topher-mcbearslayer , If we workaround to make the function moving position at the Start() event then the sub emitter can invoke. But I think this issue should fix :)

**Comment by mob-sakai** [comment] 2021-02-18 05:15
Same issue: #112 

The baked positions of all sub-emitter particles generated in the instantiated frame, were all zero. (Why?)
This means that the vertex count will increase, but the particle will not be displayed.

I have implemented a draft of the fix.
https://github.com/mob-sakai/ParticleEffectForUGUI/commit/d5ce78ae5acf2740ba7fdc6cde9f197c4e165484

@nntgam @topher-mcbearslayer (and @agrobost @yanghu28)
Could you try this?
Find the `manifest.json` file in the `Packages` folder of your project and add a line to dependencies field to install.
- `"com.coffee.ui-particle": "https://github.com/mob-sakai/ParticleEffectForUGUI.git#develop",`

If it works well, it will be released soon. 👍

**Comment by nntgam** [comment] 2021-02-18 12:45
@mob-sakai Thank for update bro, It work well.

**Comment by topher-mcbearslayer** [comment] 2021-02-18 14:11
> Same issue: #112
> 
> The baked positions of all sub-emitter particles generated in the instantiated frame, were all zero. (Why?)
> This means that the vertex count will increase, but the particle will not be displayed.
> 
> I have implemented a draft of the fix.
> [d5ce78a](https://github.com/mob-sakai/ParticleEffectForUGUI/commit/d5ce78ae5acf2740ba7fdc6cde9f197c4e165484)
> 
> @nntgam @topher-mcbearslayer (and @agrobost @yanghu28)
> Could you try this?
> Find the `manifest.json` file in the `Packages` folder of your project and add a line to dependencies field to install.
> 
> * `"com.coffee.ui-particle": "https://github.com/mob-sakai/ParticleEffectForUGUI.git#develop",`
> 
> If it works well, it will be released soon. 👍

Works! Thank you @mob-sakai!  I'll work on getting you a minimal project for the other issue today.

**Comment by mob-sakai** [comment] 2021-02-19 08:55
@nntgam @topher-mcbearslayer 
Thank you very much! 👍

**Comment by mob-sakai** [comment] 2021-02-22 12:45
Fixed in `3.3.4`

**Closed by mob-sakai** 2021-02-22 12:45 UTC
Labels: bug, released
