### ISSUE TITLE
3.3.5 Mesh bounds min=(nan, nan, nan), max=(nan, nan, nan)

### ISSUE THREAD

**Issue by HFX-93** [mob-sakai/ParticleEffectForUGUI#275] opened 2023-10-28 09:10 UTC
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following)**

- Package version [e.g. 4.2.0, 3.3.14]  3.3.5
- Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL] 
- Unity version: [e.g. 2020.3.4f1c1]
- Project options: [e.g. Mono/IL2CPP, .Net Standard 2.1/.Net 4.x, URP/HDRP, GraphicAPIs]

exception_type: Error <br> exception_message: Mesh '': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting. Mesh bounds min=(nan, nan, nan), max=(nan, nan, nan). Please make sure the mesh is exported without any errors. <br> stack_trace: Coffee.UIExtensions.UIParticleUpdater:BakeMesh(UIParticle) Coffee.UIExtensions.UIParticleUpdater:Refresh(UIParticle) Coffee.UIExtensions.UIParticleUpdater:Refresh() UnityEngine.WillRenderCanvases:Invoke() <br>
![screenshot-20231028-170753](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/22762295/c924ed33-301d-4b0e-93ea-83b51c70dd6d)

I have tried to fix this error in version 3.3.5. May I ask if this modification is correct？

Please add any other context about the issue here.
It will help us resolve the issue.

- Error messages and crash dump
- Screenshots, gif animations and movie files
- Reproducible minimal project
    - The entire project (zipped Assets, Packages, ProjectSettings) is preferred over `.unitypackage`

**Comment by HFX-93** [comment] 2023-10-31 03:01
@mob-sakai 
1、The time span from version 3.3.5 to version 4.2.2 is too big, and many special effects in the project are not suitable for version 4.2.2, so I still have to use version 3.3.5 for the time being, but I still need to solve this error. Please check whether my handling method is correct. If not, could you please provide me with a solution?

2、This is the specific error message，About 100,000 errors are reported every day：
exception_type: Error <br> exception_message: Mesh '': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting. Mesh bounds min=(nan, nan, nan), max=(nan, nan, nan). Please make sure the mesh is exported without any errors. <br> stack_trace: Coffee.UIExtensions.UIParticleUpdater:BakeMesh(UIParticle) Coffee.UIExtensions.UIParticleUpdater:Refresh(UIParticle) Coffee.UIExtensions.UIParticleUpdater:Refresh() UnityEngine.WillRenderCanvases:Invoke() <br>


![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/22762295/7dd9cf32-0225-4b2d-a45b-58ac2beec31f)

**Comment by mob-sakai** [comment] 2023-11-02 08:35
Hi @HFX-93,
thank you for your reporting.

- Similar issues:
https://github.com/mob-sakai/ParticleEffectForUGUI/issues?q=is%3Aissue+abnormal+is%3Aclosed

```diff
- s_CombineInstances[0].mesh.Clear();
+ s_CombineInstances[0].mesh.Clear(false);
```

```diff
- if (_isTrail && _parent.canSimulate)
+ if (_isTrail && _parent.canSimulate && 0 < s_CombineInstances[0].mesh.vertices.Length)
{
    _renderer.BakeTrailsMesh(s_CombineInstances[0].mesh, bakeCamera, true);
}
```

- Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?
- `Profiler.EndSample` is not needed.
- Please try version 3.3.14
- You can install the package as embed package and fix it
  - Manually copy a Unity package from the project’s package cache into your project’s Packages folder.

**Comment by HFX-93** [comment] 2023-11-02 08:50
The one you changed does not apply to my current version, I am currently using the submission on February 28, 2021, the version is 3.3.5, please give me a repair plan for my current version, thank you in advance

**Comment by mob-sakai** [comment] 2023-11-04 01:47
I would like to know more about this issue.
Tell me about your develop/build environment.
 - 〇〇 version [e.g. 3.3.10]
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac), iOS, Android, WebGL]
 - Unity version: [e.g. 2022.2.0f1]
 - Build options: [e.g. IL2CPP, .Net 4.x, URP/HDRP]
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

![repos](https://user-images.githubusercontent.com/12690315/130532459-0b5076f1-9b07-460b-b448-1d487e40ec1f.png)

**Comment by HFX-93** [comment] 2023-11-04 02:00
> I would like to know more about this issue. Tell me about your develop/build environment.
> 
> * 〇〇 version 3.3.5
> * Platform: iOS, Android
> * Unity version: 2020.3.4f1c1
> * Build options: IL2CPP、.NET Standard2.0
>  I can't reproduce this problem because it was all reported by online users, you can look at the code for version 3.3.5.

**Comment by mob-sakai** [comment] 2023-11-04 12:00
Try adding `Mesh.Clear(false)` before `BakeMesh()` and `BakeTrailsMesh()`.
However, since you did not attach a reproducible project, I cannot certify that it is the correct modification.

```diff
+ m.Clear(false);
r.BakeMesh(m, camera, true);
```

```diff
+ m.Clear(false);
r.BakeTrailsMesh(m, camera, true);
```

**Comment by HFX-93** [comment] 2023-11-04 12:05
@mob-sakai   Is that right?
![image](https://github.com/mob-sakai/ParticleEffectForUGUI/assets/22762295/509deb24-c3db-488b-af3d-566b36e3376a)

**Comment by mob-sakai** [comment] 2023-11-04 12:14
👍 
Hope they fix the issue.

**Comment by HFX-93** [comment] 2023-11-04 12:24
@mob-sakai 
The version of 4.x has changed too much compared with 3.x, and many special effects in my project will appear abnormal, what should I do about this? Besides, some special effects cannot be adjusted to normal with version 4.x, can I provide you with a project, can you help me to see what the problem is?

**Comment by mob-sakai** [comment] 2023-11-04 17:22
Of course.

- Please close this issue and create a new one.
- Please attach a minimal project that has problems when updating ParticleEffectForUGUI from v3.x to v4.x.
- Attaching a wide variety of effects will help us solve the problem.

**Closed** 2023-11-08 02:56 UTC
Labels: bug

**Comment by HFX-93** [comment] 2023-11-08 02:59
> @mob-sakai Is that right? ![image](https://user-images.githubusercontent.com/22762295/280464802-509deb24-c3db-488b-af3d-566b36e3376a.png)

@mob-sakai  If this change has no performance impact, I am ready to post it online and see if the player feedback reports the error

**Comment by mob-sakai** [comment] 2023-11-08 03:24
I don't think it will be a problem.
