### ISSUE TITLE
UIParticle.Scale does not affect the gizmo of shape module

### ISSUE THREAD

**Issue by tracer8** [mob-sakai/ParticleEffectForUGUI#21] opened 2018-12-18 10:13 UTC
Hi Mob, thank you for awesome Plugin! It working great, but have 1 inconvenience, when i use Scale factor, particle scaled, but shape of it not scale, it's still small like image bellow, i'm use canvas overlay, i must scale transform of particle to make it working correct. Please check it out, thank you so much!

And why did you need to provide Scale factor when we can use Transform Scale?

![bandicam 2018-12-18 17-07-05-352](https://user-images.githubusercontent.com/15725821/50147025-b510f880-02e7-11e9-9cd9-56c821ae1868.jpg)

**Comment by mob-sakai** [comment] 2018-12-18 11:41
Hi @tracer8 
Thank you for reporting!

I would like to know more information on this issue.
Can you submit a reproducible project for this issue?

**Comment by tracer8** [comment] 2018-12-18 12:09
I'm not on Pc now but you can create 1 particle to game object on world
space, then put it in canvas overlay after that try Scale particles use
UIParticle Scale variable, then check your Particle Shape size.

**Comment by mob-sakai** [comment] 2018-12-18 12:31
Oh, I understood.
"Shape" is not about Shape module, right?

**Comment by tracer8** [comment] 2018-12-18 12:32
yes, it's settings of particle like emission, color over life time, size
over life time etc...v...v...

**Comment by tracer8** [comment] 2018-12-18 12:34
it's where you choose emit like cone, box, sphere...v...v...

**Comment by mob-sakai** [comment] 2018-12-18 13:49
I tested the following steps on Unity 2018.3.f1:
* Click `GameObject > Effects > ParticleSystem`
* Put it in canvas overlay
* Add UIParticle component to it
* Reset the transform position and scale
* Play editor
* Change UIParticle.Scale property

**Result:** It seems to be working well...
![](https://user-images.githubusercontent.com/12690315/50158232-ec4ace00-0316-11e9-98a1-889b7c915e26.gif)

**Comment by tracer8** [comment] 2018-12-18 14:05
Agh yeah, it's working very good. What i mean is gizmos size of shape , so i can modify it through Scene view. Sorry for misleading :D

 You can see bellow, what i mention is shape :
![bandicam 2018-12-18 21-00-07-286](https://user-images.githubusercontent.com/15725821/50159104-6aec3f00-0308-11e9-97f7-1abd953f9a34.jpg)

If i use Scale property, it's still small like this:
![bandicam 2018-12-18 21-01-40-703](https://user-images.githubusercontent.com/15725821/50159133-7e97a580-0308-11e9-9960-622637130783.jpg)

If i use transform scale, it will scale this gizmos box of shape will scale too, so i can edit it from Scene view: 
![bandicam 2018-12-18 21-01-37-687](https://user-images.githubusercontent.com/15725821/50159126-78092e00-0308-11e9-9552-46d9a7240b7e.jpg)

**Comment by mob-sakai** [comment] 2018-12-18 23:12
I completely understand.

The gizmo is drawn by ParticleSystemInspector.
UIParticle.Scale has no effect on it.

I think that this issue will be solved by drawing scaled gizmo by UIParticleEditor.

**Comment by mob-sakai** [comment] 2018-12-20 01:19
[WIP] prototype gizmo (purple line)
![dec-20-2018 10-17-25](https://user-images.githubusercontent.com/12690315/50257895-a12cda00-0440-11e9-95c1-421605495a3d.gif)

**Comment by tracer8** [comment] 2018-12-20 01:33
Sweet! 😆

**Comment by mob-sakai** [comment] 2018-12-21 13:03
**Scaled gizmo** will be released soon.
![](https://user-images.githubusercontent.com/12690315/50343861-f31e4e80-056b-11e9-8f60-8bd0a8ff7adb.gif)

**Closed** 2018-12-21 13:06 UTC
Labels: bug
